# Generated by Django 4.2.30 on 2026-09-22

from django.db import migrations, models


class Migration(migrations.Migration):
    """Add map activity and chart telemetry fields."""

    dependencies = [
        ("api", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="location",
            name="is_active",
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name="sensormeasurement",
            name="pressure",
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="sensormeasurement",
            name="wind_speed",
            field=models.FloatField(blank=True, null=True),
        ),
    ]
